### ISSUE TITLE
no release

### ISSUE THREAD

**Issue by Pr-Codee** [SplitgateDevelopment/Launcher#1]

**Comment by 47PADO47** [comment]
After 90 days of retention github deletes the artifacts, so you can't download them anymore because they expired.
Also latest CI was failing and i haven't had time to look into it, therefore the only option remaining is compiling it your self using vs 2022. To do it you must have python installed, install git submodules (pybind11) and update Internal/Internal.vcxproj replacing C:\Python310 with your python location.
